package model;

import java.sql.Timestamp;
import java.util.Date;

public class ProductAccessory{
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_accessory.produce_date
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
   private Timestamp produceDate;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_accessory.furnace_num
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
   private String furnaceNum;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_accessory.accessory_name
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
   private String accessoryName;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_accessory.addtime
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
   private Integer addTime;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_accessory.produce_date
    *
    * @return the value of product_accessory.produce_date
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
    private String classNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_accessory.addweight
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private Integer addWeight;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_accessory.produce_date
     *
     * @return the value of product_accessory.produce_date
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public Date getProduceDate() {
        return produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_accessory.produce_date
     *
     * @param produceDate the value for product_accessory.produce_date
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setProduceDate(Timestamp produceDate) {
        this.produceDate = produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_accessory.furnace_num
     *
     * @return the value of product_accessory.furnace_num
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public String getFurnaceNum() {
        return furnaceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_accessory.furnace_num
     *
     * @param furnaceNum the value for product_accessory.furnace_num
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setFurnaceNum(String furnaceNum) {
        this.furnaceNum = furnaceNum == null ? null : furnaceNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_accessory.accessory_name
     *
     * @return the value of product_accessory.accessory_name
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public String getAccessoryName() {
        return accessoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_accessory.accessory_name
     *
     * @param accessoryName the value for product_accessory.accessory_name
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setAccessoryName(String accessoryName) {
        this.accessoryName = accessoryName == null ? null : accessoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_accessory.addtime
     *
     * @return the value of product_accessory.addtime
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public Integer getAddtime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_accessory.addtime
     *
     * @param addtime the value for product_accessory.addtime
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setAddtime(Integer addtime) {
        this.addTime = addtime;
    }
    public String getClassNo() {
        return classNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_accessory.class_no
     *
     * @param classNo the value for product_accessory.class_no
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setClassNo(String classNo) {
        this.classNo = classNo == null ? null : classNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_accessory.addweight
     *
     * @return the value of product_accessory.addweight
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public Integer getAddweight() {
        return addWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_accessory.addweight
     *
     * @param addweight the value for product_accessory.addweight
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setAddweight(Integer addweight) {
        this.addWeight = addweight;
    }

	@Override
	public String toString() {
		return "ProductAccessory [produceDate=" + produceDate + ", furnaceNum=" + furnaceNum + ", accessoryName="
				+ accessoryName + ", addtime=" + addTime + ", classNo=" + classNo + ", addweight=" + addWeight + "]";
	}
    
    
}