package model;

import java.sql.Timestamp;
import java.util.Date;

public class ProductAlloy{
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_alloy.produce_date
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
   private Timestamp produceDate;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_alloy.furnace_num
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
   private String furnaceNum;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_alloy.alloy_name
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
   private String alloyName;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_alloy.addtime
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
   private Integer addtime;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_alloy.produce_date
    *
    * @return the value of product_alloy.produce_date
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
    private String classNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_alloy.addweight
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private Integer addweight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_alloy.class_no
     *
     * @return the value of product_alloy.class_no
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public Date getProduceDate() {
        return produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_alloy.produce_date
     *
     * @param produceDate the value for product_alloy.produce_date
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setProduceDate(Timestamp produceDate) {
        this.produceDate = produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_alloy.furnace_num
     *
     * @return the value of product_alloy.furnace_num
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public String getFurnaceNum() {
        return furnaceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_alloy.furnace_num
     *
     * @param furnaceNum the value for product_alloy.furnace_num
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setFurnaceNum(String furnaceNum) {
        this.furnaceNum = furnaceNum == null ? null : furnaceNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_alloy.alloy_name
     *
     * @return the value of product_alloy.alloy_name
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public String getAlloyName() {
        return alloyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_alloy.alloy_name
     *
     * @param alloyName the value for product_alloy.alloy_name
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setAlloyName(String alloyName) {
        this.alloyName = alloyName == null ? null : alloyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_alloy.addtime
     *
     * @return the value of product_alloy.addtime
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_alloy.addtime
     *
     * @param addtime the value for product_alloy.addtime
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }
    
    public String getClassNo() {
        return classNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_alloy.class_no
     *
     * @param classNo the value for product_alloy.class_no
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setClassNo(String classNo) {
        this.classNo = classNo == null ? null : classNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_alloy.addweight
     *
     * @return the value of product_alloy.addweight
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public Integer getAddweight() {
        return addweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_alloy.addweight
     *
     * @param addweight the value for product_alloy.addweight
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setAddweight(Integer addweight) {
        this.addweight = addweight;
    }

	@Override
	public String toString() {
		return "ProductAlloy [produceDate=" + produceDate + ", furnaceNum=" + furnaceNum + ", alloyName=" + alloyName
				+ ", addtime=" + addtime + ", classNo=" + classNo + ", addweight=" + addweight + "]";
	}
    
    
}