package model;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

public class ProductSlag {
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_slag.produce_date
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
   private Timestamp produceDate;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_slag.furnace_num
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
   private String furnaceNum;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_slag.produce_date
    *
    * @return the value of product_slag.produce_date
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
    private String classNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_slag.FeO
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal feo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_slag.SiO2
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal sio2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_slag.CaO
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal cao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_slag.MgO
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal mgo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_slag.R
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal r;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_slag.class_no
     *
     * @return the value of product_slag.class_no
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    
    public Date getProduceDate() {
        return produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_slag.produce_date
     *
     * @param produceDate the value for product_slag.produce_date
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setProduceDate(Timestamp produceDate) {
        this.produceDate = produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_slag.furnace_num
     *
     * @return the value of product_slag.furnace_num
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public String getFurnaceNum() {
        return furnaceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_slag.furnace_num
     *
     * @param furnaceNum the value for product_slag.furnace_num
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setFurnaceNum(String furnaceNum) {
        this.furnaceNum = furnaceNum == null ? null : furnaceNum.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_slag.furnace_num
     *
     * @param furnaceNum the value for product_slag.furnace_num
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public String getClassNo() {
        return classNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_slag.class_no
     *
     * @param classNo the value for product_slag.class_no
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setClassNo(String classNo) {
        this.classNo = classNo == null ? null : classNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_slag.FeO
     *
     * @return the value of product_slag.FeO
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getFeo() {
        return feo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_slag.FeO
     *
     * @param feo the value for product_slag.FeO
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setFeo(BigDecimal feo) {
        this.feo = feo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_slag.SiO2
     *
     * @return the value of product_slag.SiO2
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getSio2() {
        return sio2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_slag.SiO2
     *
     * @param sio2 the value for product_slag.SiO2
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setSio2(BigDecimal sio2) {
        this.sio2 = sio2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_slag.CaO
     *
     * @return the value of product_slag.CaO
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getCao() {
        return cao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_slag.CaO
     *
     * @param cao the value for product_slag.CaO
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setCao(BigDecimal cao) {
        this.cao = cao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_slag.MgO
     *
     * @return the value of product_slag.MgO
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getMgo() {
        return mgo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_slag.MgO
     *
     * @param mgo the value for product_slag.MgO
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setMgo(BigDecimal mgo) {
        this.mgo = mgo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_slag.R
     *
     * @return the value of product_slag.R
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getR() {
        return r;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_slag.R
     *
     * @param r the value for product_slag.R
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setR(BigDecimal r) {
        this.r = r;
    }

	@Override
	public String toString() {
		return "ProductSlag [produceDate=" + produceDate + ", furnaceNum=" + furnaceNum + ", classNo=" + classNo
				+ ", feo=" + feo + ", sio2=" + sio2 + ", cao=" + cao + ", mgo=" + mgo + ", r=" + r + "]";
	}
    
}