package model;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class ProductParameter {
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_parameter.produce_date
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
	
   @DateTimeFormat(pattern = "yyyy-MM-dd")
   @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8") 	
   private Date produceDate;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_parameter.furnace_num
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
   private String furnaceNum;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_parameter.produce_date
    *
    * @return the value of product_parameter.produce_date
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
	
    private String classNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.furnace_no
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private String furnaceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.furnace_age
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private String furnaceAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.steel_name
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private String steelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.oxygun1
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private Integer oxygun1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.oxygun2
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private Integer oxygun2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.oxymode
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private Integer oxymode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.iron_c
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal ironC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.iron_si
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal ironSi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.iron_mn
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal ironMn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.iron_p
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal ironP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.iron_s
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal ironS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.iron_temperature
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private String ironTemperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.outlet_age
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private Integer outletAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.iron_weight
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal ironWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.resteel_weight1
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal resteelWeight1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.resteel_weight2
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal resteelWeight2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.steel_weight
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal steelWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.pro_oxytime1
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal proOxytime1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.pro_oxyval
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private Integer proOxyval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.turn_num
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private Integer turnNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.turn_temperature1
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private Integer turnTemperature1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.pro_oxytime2
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal proOxytime2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.turn_temperature2
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private Integer turnTemperature2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.pro_nval
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private Integer proNval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.slag_time
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal slagTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.slag_weight
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private Integer slagWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.turn_c
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal turnC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.turn_s
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal turnS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.turn_p
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal turnP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.turn_mn
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal turnMn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.steel_dir
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private Integer steelDir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.steel_fe
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private Integer steelFe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_parameter.steel_remark
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private String steelRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.class_no
     *
     * @return the value of product_parameter.class_no
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    
    public ProductParameter() {
		super();
		// TODO Auto-generated constructor stub
	}

    
    public Date getProduceDate() {
        return produceDate;
    }

    
	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.produce_date
     *
     * @param produceDate the value for product_parameter.produce_date
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setProduceDate(Date produceDate) {
        this.produceDate = produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.furnace_num
     *
     * @return the value of product_parameter.furnace_num
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public String getFurnaceNum() {
        return furnaceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.furnace_num
     *
     * @param furnaceNum the value for product_parameter.furnace_num
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setFurnaceNum(String furnaceNum) {
        this.furnaceNum = furnaceNum == null ? null : furnaceNum.trim();
    }
    public String getClassNo() {
        return classNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.class_no
     *
     * @param classNo the value for product_parameter.class_no
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setClassNo(String classNo) {
        this.classNo = classNo == null ? null : classNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.furnace_no
     *
     * @return the value of product_parameter.furnace_no
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public String getFurnaceNo() {
        return furnaceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.furnace_no
     *
     * @param furnaceNo the value for product_parameter.furnace_no
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setFurnaceNo(String furnaceNo) {
        this.furnaceNo = furnaceNo == null ? null : furnaceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.furnace_age
     *
     * @return the value of product_parameter.furnace_age
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public String getFurnaceAge() {
        return furnaceAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.furnace_age
     *
     * @param furnaceAge the value for product_parameter.furnace_age
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setFurnaceAge(String furnaceAge) {
        this.furnaceAge = furnaceAge == null ? null : furnaceAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.steel_name
     *
     * @return the value of product_parameter.steel_name
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public String getSteelName() {
        return steelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.steel_name
     *
     * @param steelName the value for product_parameter.steel_name
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setSteelName(String steelName) {
        this.steelName = steelName == null ? null : steelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.oxygun1
     *
     * @return the value of product_parameter.oxygun1
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public Integer getOxygun1() {
        return oxygun1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.oxygun1
     *
     * @param oxygun1 the value for product_parameter.oxygun1
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setOxygun1(Integer oxygun1) {
        this.oxygun1 = oxygun1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.oxygun2
     *
     * @return the value of product_parameter.oxygun2
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public Integer getOxygun2() {
        return oxygun2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.oxygun2
     *
     * @param oxygun2 the value for product_parameter.oxygun2
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setOxygun2(Integer oxygun2) {
        this.oxygun2 = oxygun2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.oxymode
     *
     * @return the value of product_parameter.oxymode
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public Integer getOxymode() {
        return oxymode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.oxymode
     *
     * @param oxymode the value for product_parameter.oxymode
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setOxymode(Integer oxymode) {
        this.oxymode = oxymode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.iron_c
     *
     * @return the value of product_parameter.iron_c
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getIronC() {
        return ironC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.iron_c
     *
     * @param ironC the value for product_parameter.iron_c
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setIronC(BigDecimal ironC) {
        this.ironC = ironC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.iron_si
     *
     * @return the value of product_parameter.iron_si
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getIronSi() {
        return ironSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.iron_si
     *
     * @param ironSi the value for product_parameter.iron_si
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setIronSi(BigDecimal ironSi) {
        this.ironSi = ironSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.iron_mn
     *
     * @return the value of product_parameter.iron_mn
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getIronMn() {
        return ironMn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.iron_mn
     *
     * @param ironMn the value for product_parameter.iron_mn
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setIronMn(BigDecimal ironMn) {
        this.ironMn = ironMn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.iron_p
     *
     * @return the value of product_parameter.iron_p
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getIronP() {
        return ironP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.iron_p
     *
     * @param ironP the value for product_parameter.iron_p
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setIronP(BigDecimal ironP) {
        this.ironP = ironP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.iron_s
     *
     * @return the value of product_parameter.iron_s
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getIronS() {
        return ironS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.iron_s
     *
     * @param ironS the value for product_parameter.iron_s
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setIronS(BigDecimal ironS) {
        this.ironS = ironS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.iron_temperature
     *
     * @return the value of product_parameter.iron_temperature
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public String getIronTemperature() {
        return ironTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.iron_temperature
     *
     * @param ironTemperature the value for product_parameter.iron_temperature
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setIronTemperature(String ironTemperature) {
        this.ironTemperature = ironTemperature == null ? null : ironTemperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.outlet_age
     *
     * @return the value of product_parameter.outlet_age
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public Integer getOutletAge() {
        return outletAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.outlet_age
     *
     * @param outletAge the value for product_parameter.outlet_age
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setOutletAge(Integer outletAge) {
        this.outletAge = outletAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.iron_weight
     *
     * @return the value of product_parameter.iron_weight
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getIronWeight() {
        return ironWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.iron_weight
     *
     * @param ironWeight the value for product_parameter.iron_weight
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setIronWeight(BigDecimal ironWeight) {
        this.ironWeight = ironWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.resteel_weight1
     *
     * @return the value of product_parameter.resteel_weight1
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getResteelWeight1() {
        return resteelWeight1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.resteel_weight1
     *
     * @param resteelWeight1 the value for product_parameter.resteel_weight1
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setResteelWeight1(BigDecimal resteelWeight1) {
        this.resteelWeight1 = resteelWeight1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.resteel_weight2
     *
     * @return the value of product_parameter.resteel_weight2
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getResteelWeight2() {
        return resteelWeight2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.resteel_weight2
     *
     * @param resteelWeight2 the value for product_parameter.resteel_weight2
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setResteelWeight2(BigDecimal resteelWeight2) {
        this.resteelWeight2 = resteelWeight2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.steel_weight
     *
     * @return the value of product_parameter.steel_weight
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getSteelWeight() {
        return steelWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.steel_weight
     *
     * @param steelWeight the value for product_parameter.steel_weight
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setSteelWeight(BigDecimal steelWeight) {
        this.steelWeight = steelWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.pro_oxytime1
     *
     * @return the value of product_parameter.pro_oxytime1
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getProOxytime1() {
        return proOxytime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.pro_oxytime1
     *
     * @param proOxytime1 the value for product_parameter.pro_oxytime1
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setProOxytime1(BigDecimal proOxytime1) {
        this.proOxytime1 = proOxytime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.pro_oxyval
     *
     * @return the value of product_parameter.pro_oxyval
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public Integer getProOxyval() {
        return proOxyval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.pro_oxyval
     *
     * @param proOxyval the value for product_parameter.pro_oxyval
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setProOxyval(Integer proOxyval) {
        this.proOxyval = proOxyval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.turn_num
     *
     * @return the value of product_parameter.turn_num
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public Integer getTurnNum() {
        return turnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.turn_num
     *
     * @param turnNum the value for product_parameter.turn_num
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setTurnNum(Integer turnNum) {
        this.turnNum = turnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.turn_temperature1
     *
     * @return the value of product_parameter.turn_temperature1
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public Integer getTurnTemperature1() {
        return turnTemperature1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.turn_temperature1
     *
     * @param turnTemperature1 the value for product_parameter.turn_temperature1
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setTurnTemperature1(Integer turnTemperature1) {
        this.turnTemperature1 = turnTemperature1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.pro_oxytime2
     *
     * @return the value of product_parameter.pro_oxytime2
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getProOxytime2() {
        return proOxytime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.pro_oxytime2
     *
     * @param proOxytime2 the value for product_parameter.pro_oxytime2
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setProOxytime2(BigDecimal proOxytime2) {
        this.proOxytime2 = proOxytime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.turn_temperature2
     *
     * @return the value of product_parameter.turn_temperature2
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public Integer getTurnTemperature2() {
        return turnTemperature2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.turn_temperature2
     *
     * @param turnTemperature2 the value for product_parameter.turn_temperature2
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setTurnTemperature2(Integer turnTemperature2) {
        this.turnTemperature2 = turnTemperature2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.pro_nval
     *
     * @return the value of product_parameter.pro_nval
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public Integer getProNval() {
        return proNval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.pro_nval
     *
     * @param proNval the value for product_parameter.pro_nval
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setProNval(Integer proNval) {
        this.proNval = proNval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.slag_time
     *
     * @return the value of product_parameter.slag_time
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getSlagTime() {
        return slagTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.slag_time
     *
     * @param slagTime the value for product_parameter.slag_time
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setSlagTime(BigDecimal slagTime) {
        this.slagTime = slagTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.slag_weight
     *
     * @return the value of product_parameter.slag_weight
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public Integer getSlagWeight() {
        return slagWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.slag_weight
     *
     * @param slagWeight the value for product_parameter.slag_weight
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setSlagWeight(Integer slagWeight) {
        this.slagWeight = slagWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.turn_c
     *
     * @return the value of product_parameter.turn_c
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getTurnC() {
        return turnC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.turn_c
     *
     * @param turnC the value for product_parameter.turn_c
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setTurnC(BigDecimal turnC) {
        this.turnC = turnC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.turn_s
     *
     * @return the value of product_parameter.turn_s
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getTurnS() {
        return turnS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.turn_s
     *
     * @param turnS the value for product_parameter.turn_s
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setTurnS(BigDecimal turnS) {
        this.turnS = turnS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.turn_p
     *
     * @return the value of product_parameter.turn_p
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getTurnP() {
        return turnP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.turn_p
     *
     * @param turnP the value for product_parameter.turn_p
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setTurnP(BigDecimal turnP) {
        this.turnP = turnP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.turn_mn
     *
     * @return the value of product_parameter.turn_mn
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getTurnMn() {
        return turnMn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.turn_mn
     *
     * @param turnMn the value for product_parameter.turn_mn
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setTurnMn(BigDecimal turnMn) {
        this.turnMn = turnMn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.steel_dir
     *
     * @return the value of product_parameter.steel_dir
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public Integer getSteelDir() {
        return steelDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.steel_dir
     *
     * @param steelDir the value for product_parameter.steel_dir
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setSteelDir(Integer steelDir) {
        this.steelDir = steelDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.steel_fe
     *
     * @return the value of product_parameter.steel_fe
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public Integer getSteelFe() {
        return steelFe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.steel_fe
     *
     * @param steelFe the value for product_parameter.steel_fe
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setSteelFe(Integer steelFe) {
        this.steelFe = steelFe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_parameter.steel_remark
     *
     * @return the value of product_parameter.steel_remark
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public String getSteelRemark() {
        return steelRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_parameter.steel_remark
     *
     * @param steelRemark the value for product_parameter.steel_remark
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setSteelRemark(String steelRemark) {
        this.steelRemark = steelRemark == null ? null : steelRemark.trim();
    }

	@Override
	public String toString() {
		return "ProductParameter [produceDate=" + produceDate + ", furnaceNum=" + furnaceNum + ", classNo=" + classNo
				+ ", furnaceNo=" + furnaceNo + ", furnaceAge=" + furnaceAge + ", steelName=" + steelName + ", oxygun1="
				+ oxygun1 + ", oxygun2=" + oxygun2 + ", oxymode=" + oxymode + ", ironC=" + ironC + ", ironSi=" + ironSi
				+ ", ironMn=" + ironMn + ", ironP=" + ironP + ", ironS=" + ironS + ", ironTemperature="
				+ ironTemperature + ", outletAge=" + outletAge + ", ironWeight=" + ironWeight + ", resteelWeight1="
				+ resteelWeight1 + ", resteelWeight2=" + resteelWeight2 + ", steelWeight=" + steelWeight
				+ ", proOxytime1=" + proOxytime1 + ", proOxyval=" + proOxyval + ", turnNum=" + turnNum
				+ ", turnTemperature1=" + turnTemperature1 + ", proOxytime2=" + proOxytime2 + ", turnTemperature2="
				+ turnTemperature2 + ", proNval=" + proNval + ", slagTime=" + slagTime + ", slagWeight=" + slagWeight
				+ ", turnC=" + turnC + ", turnS=" + turnS + ", turnP=" + turnP + ", turnMn=" + turnMn + ", steelDir="
				+ steelDir + ", steelFe=" + steelFe + ", steelRemark=" + steelRemark + "]";
	}

	
    
    
}