package model;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

public class ProductSteel{
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_steel.steel_name
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
   private String steelName;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_steel.produce_date
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
   
   private String classNo;
   
   private Timestamp produceDate;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_steel.furnace_num
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
   private String furnaceNum;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_steel.steel_name
    *
    * @return the value of product_steel.steel_name
    *
    * @mbg.generated Fri Nov 13 14:31:19 CST 2020
    */
    private BigDecimal steelC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_steel.steel_si
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal steelSi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_steel.steel_mn
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal steelMn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_steel.steel_p
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal steelP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_steel.steel_s
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal steelS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_steel.steel_als
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal steelAls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_steel.steel_ti
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal steelTi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_steel.steel_nb
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    private BigDecimal steelNb;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_steel.steel_c
     *
     * @return the value of product_steel.steel_c
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public String getSteelName() {
        return steelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_steel.steel_name
     *
     * @param steelName the value for product_steel.steel_name
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setSteelName(String steelName) {
        this.steelName = steelName == null ? null : steelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_steel.produce_date
     *
     * @return the value of product_steel.produce_date
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    
    public String getClassNo() {
		return classNo;
	}

	public void setClassNo(String classNo) {
		this.classNo = classNo;
	}

    public Date getProduceDate() {
        return produceDate;
    }

    
	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_steel.produce_date
     *
     * @param produceDate the value for product_steel.produce_date
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setProduceDate(Timestamp produceDate) {
        this.produceDate = produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_steel.furnace_num
     *
     * @return the value of product_steel.furnace_num
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public String getFurnaceNum() {
        return furnaceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_steel.furnace_num
     *
     * @param furnaceNum the value for product_steel.furnace_num
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setFurnaceNum(String furnaceNum) {
        this.furnaceNum = furnaceNum == null ? null : furnaceNum.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_steel.furnace_num
     *
     * @param furnaceNum the value for product_steel.furnace_num
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getSteelC() {
        return steelC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_steel.steel_c
     *
     * @param steelC the value for product_steel.steel_c
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setSteelC(BigDecimal steelC) {
        this.steelC = steelC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_steel.steel_si
     *
     * @return the value of product_steel.steel_si
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getSteelSi() {
        return steelSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_steel.steel_si
     *
     * @param steelSi the value for product_steel.steel_si
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setSteelSi(BigDecimal steelSi) {
        this.steelSi = steelSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_steel.steel_mn
     *
     * @return the value of product_steel.steel_mn
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getSteelMn() {
        return steelMn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_steel.steel_mn
     *
     * @param steelMn the value for product_steel.steel_mn
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setSteelMn(BigDecimal steelMn) {
        this.steelMn = steelMn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_steel.steel_p
     *
     * @return the value of product_steel.steel_p
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getSteelP() {
        return steelP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_steel.steel_p
     *
     * @param steelP the value for product_steel.steel_p
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setSteelP(BigDecimal steelP) {
        this.steelP = steelP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_steel.steel_s
     *
     * @return the value of product_steel.steel_s
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getSteelS() {
        return steelS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_steel.steel_s
     *
     * @param steelS the value for product_steel.steel_s
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setSteelS(BigDecimal steelS) {
        this.steelS = steelS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_steel.steel_als
     *
     * @return the value of product_steel.steel_als
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getSteelAls() {
        return steelAls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_steel.steel_als
     *
     * @param steelAls the value for product_steel.steel_als
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setSteelAls(BigDecimal steelAls) {
        this.steelAls = steelAls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_steel.steel_ti
     *
     * @return the value of product_steel.steel_ti
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getSteelTi() {
        return steelTi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_steel.steel_ti
     *
     * @param steelTi the value for product_steel.steel_ti
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setSteelTi(BigDecimal steelTi) {
        this.steelTi = steelTi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_steel.steel_nb
     *
     * @return the value of product_steel.steel_nb
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public BigDecimal getSteelNb() {
        return steelNb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_steel.steel_nb
     *
     * @param steelNb the value for product_steel.steel_nb
     *
     * @mbg.generated Fri Nov 13 14:31:19 CST 2020
     */
    public void setSteelNb(BigDecimal steelNb) {
        this.steelNb = steelNb;
    }

	@Override
	public String toString() {
		return "ProductSteel [steelName=" + steelName + ", classNo=" + classNo + "produceDate=" + produceDate + ", furnaceNum=" + furnaceNum
				+ ", steelC=" + steelC + ", steelSi=" + steelSi + ", steelMn=" + steelMn + ", steelP=" + steelP
				+ ", steelS=" + steelS + ", steelAls=" + steelAls + ", steelTi=" + steelTi + ", steelNb=" + steelNb
				+ "]";
	}
    
}